export const users = [
    {nombre: 'Pedro', edad: 15},
    {nombre: 'Sofia', edad: 23},
    {nombre: 'Julia', edad: 50},
    {nombre: 'Andres', edad: 80},
    {nombre: 'Sandro', edad: 45},
    {nombre: 'Peter', edad: 20},
    {nombre: 'Antonio', edad: 10},
    {nombre: 'Harold', edad: 35},
    {nombre: 'Nicolas', edad: 38},
    {nombre: 'Andrea', edad: 60},
    {nombre: 'Briana', edad: 37},
    {nombre: 'Katherine', edad: 67},
    {nombre: 'Rita', edad: 19},
    {nombre: 'Alicia', edad: 25},
    {nombre: 'Gianna', edad: 95},
    {nombre: 'Roberto', edad: 55},
    {nombre: 'Juana', edad: 78},
    {nombre: 'Gianella', edad: 18},
]